---
- name: drop monitor.ldif file
  template:
    src: "monitor.ldif.j2"
    dest: "/tmp/monitor.ldif"
    mode: 0644
  tags:
    - ldap-monitor
    - ldap-ldif-files

- name: config ldap monitor
  command: "ldapmodify -w {{ ldap_admin_info.admin_password }} -Y EXTERNAL -H ldapi:/// -f /tmp/monitor.ldif"
  register: ldap_monitor
  changed_when: ldap_monitor.rc != 0
  notify:
    - restart ldap
  tags:
    - ldap-monitor
