---
- name: setup ldap database
  command: "cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG"
  register: setup_database
  failed_when: false
  changed_when: setup_database.rc != 0
  tags:
    - setup_database

- name: change database ownership
  shell: |
    if [ -f /var/lib/ldap/DB_CONFIG ]; then
       chown -R ldap:ldap /var/lib/ldap/*
    fi
  register: db_ownership
  changed_when: db_ownership.rc != 0
  tags:
    - setup_database

- name: config ldap schemas
  command: "{{ item }}"
  register: ldap_schemas
  failed_when: false
  changed_when: ldap_schemas.rc != 0
  with_items:
    - "ldapadd -w {{ ldap_admin_info.admin_password }} -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif"
    - "ldapadd -w {{ ldap_admin_info.admin_password }} -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif"
    - "ldapadd -w {{ ldap_admin_info.admin_password }} -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif"
  notify:
    - restart ldap
  when: 
   - ldap_ha_mode | lower != 'mm'
  tags:
    - setup_database
